image: th0br0/iota-buildenv:latest

stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test64:
  stage: test
  script:
    - tools/ci/build.sh 64

test32:
  stage: test
  script:
    - tools/ci/build.sh 32

